name: "Create Pull Request"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - run: git checkout -b workflow/`uuidgen`
      - run: mkdir -p rotate-files && touch rotate-files/`date +%Y-%m-%d-%H%M%S`.txt
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit -a -m "auto commit"
      - run: gh pr create --fill
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}