name: "Create Pull Request"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - run: git config --list
      - run: git status
      - run: git branch
      - run: gh auth status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: gh auth setup-git
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git config --list
      - run: git checkout -b workflow/`uuidgen`
      - run: mkdir -p rotate-files && touch rotate-files/`date +%Y-%m-%d-%H%M%S`.txt
      - run: git add .
      - run: git commit -m "auto commit"